const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless: true, executablePath: process.env.CHROME_PATH || undefined, args: ['--no-sandbox', '--disable-webgl']});
  const page = await browser.newPage({viewport: {width: 1440, height: 900}});
  page.setDefaultTimeout(30000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    const NativeAudio = window.Audio;
    window.Audio = class extends NativeAudio { constructor(...args) { super(...args); window.testRadioAudio = this; } };
  });
  await page.goto('http://127.0.0.1:8766/web/');
  await page.click('#menuRadio');
  assert.equal(await page.locator('#radioSelect option').count(), 4);
  await page.click('#radioToggle');
  await page.waitForFunction(() => testRadioAudio.currentTime > .1 && !testRadioAudio.paused);
  for (let index = 0; index < 7; index++) {
    if (index === 4) await page.selectOption('#radioPack', 'cloud');
    await page.selectOption('#radioSelect', String(index));
    await page.waitForFunction(i => testRadioAudio.currentSrc.endsWith(streetRadioTracks[i].file) && testRadioAudio.readyState >= 2 && !testRadioAudio.paused && testRadioAudio.currentTime > .05, index);
    const duration = await page.evaluate(() => testRadioAudio.duration);
    assert.ok(Number.isFinite(duration) && duration > 90, 'Real MP3 must decode');
  }
  await page.click('#radioNext');
  await page.waitForFunction(() => testRadioAudio.currentSrc.endsWith('zizkov-afterhours.mp3') && !testRadioAudio.paused);
  await page.evaluate(() => testRadioAudio.dispatchEvent(new Event('ended')));
  await page.waitForFunction(() => testRadioAudio.currentSrc.endsWith('vinohrady-clouds.mp3') && !testRadioAudio.paused);
  await page.locator('#radioVolume').fill('37');
  assert.equal(await page.evaluate(() => testRadioAudio.volume), .37);
  await page.click('#radioToggle');
  assert.equal(await page.evaluate(() => testRadioAudio.paused), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#radioOverlay').isVisible(), false);
  await page.reload();
  await page.click('#menuRadio');
  assert.equal(await page.locator('#radioPack').inputValue(), 'cloud');
  assert.equal(await page.locator('#radioSelect').inputValue(), '5');
  assert.equal(await page.locator('#radioVolume').inputValue(), '37');
  assert.equal(await page.evaluate(() => testRadioAudio.paused), true);
  await page.click('#radioToggle');
  await page.waitForFunction(() => !testRadioAudio.paused);
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  assert.equal(await page.evaluate(() => testRadioAudio.paused), true);
  await page.click('#radioToggle');
  await page.waitForFunction(() => !testRadioAudio.paused);
  fs.mkdirSync('ui-reports', {recursive: true});
  await page.screenshot({path: 'ui-reports/09-radio.png'});
  await page.setViewportSize({width: 844, height: 390});
  await page.addStyleTag({path: 'android/app/src/main/mobile/mobile.css'});
  await page.addScriptTag({path: 'android/app/src/main/mobile/mobile.js'});
  await page.locator('#radioClose').scrollIntoViewIfNeeded();
  await page.click('#radioClose');
  await page.click('#menuRadio');
  await page.screenshot({path: 'ui-reports/10-radio-mobile.png'});
  await page.click('#radioClose');
  await page.fill('#characterName', 'Radio Tester');
  await page.click('#start');
  await page.click('#radioButton');
  assert.equal(await page.locator('#radioOverlay').isVisible(), true);
  await page.route('**/audio/*.mp3', route => route.fulfill({status: 404, body: 'missing'}));
  await page.reload();
  await page.click('#menuRadio');
  await page.click('#radioToggle');
  await page.waitForFunction(() => document.getElementById('radioStatus').textContent.includes('nejsou dostupné'));
  assert.equal(await page.evaluate(() => testRadioAudio.paused), true);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: all seven MP3s decode/play, pack looping, ended/next, volume/mute persistence, blur pause, mobile controls and bounded missing-file fallback');
})().catch(error => { console.error(error); process.exit(1); });
